#Workflow
# 1. Get current config
# 2. Get desired config (templated host vars)
# 3. Find lines in current config that aren't in desired config, append "no "
# 4. Append desired config to end of list
# 5. Send to device

- name: Get current static route configuration
  cisco.ios.ios_command:
    commands:
      - show run | include ip route
  register: ip_routes

- name: Get desired static route configuration
  set_fact:
    desired_ip_routes: "{{ lookup('template', 'templates/xe_desired_ip_routes.j2') }}"

- name: Find bad lines in current config
  set_fact:
    current_diff: "{{ lookup('template', 'templates/xe_current_diff.j2') }}"

- name: combine bad lines with desired
  set_fact:
    final_output: "{{ lookup('template', 'templates/xe_final_output.j2') }}"

- name: Send config to device
  cisco.ios.ios_config:
    lines: "{{ final_output }}"
