
- name: Get current static route configuration
  cisco.nxos.nxos_command:
    commands:
      - show run | include "ip route"
  register: ip_routes

- name: Get desired configs
  set_fact:
    desired_ip_routes: "{{ lookup('template', 'templates/nxos_desired_ip_routes.j2') }}"

- name: Find bad lines in current config
  set_fact:
    current_diff: "{{ lookup('template', 'templates/nxos_current_diff.j2') }}"

- name: Combine bad lines with desired
  set_fact:
    final_output: "{{ lookup('template', 'templates/final_output.j2') }}"

- name: Send config to device
  cisco.nxos.nxos_config:
    lines: "{{ final_output }}"


